### ISSUE TITLE
[bug]: multiple downloads did not work

### ISSUE THREAD

**Issue by McTom234** [berndgz/lnxngfmsdm#4]
Downloading `X-Plane 12` and `FlightFactor Boeing 777v2` did not work.

Log:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "lnxngfmsdm_gui.py", line 360, in <lambda>
  File "lnxngfmsdm_core.py", line 233, in download
  File "selenium/webdriver/remote/webelement.py", line 94, in click
  File "selenium/webdriver/remote/webelement.py", line 395, in _execute
  File "selenium/webdriver/remote/webdriver.py", line 354, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button _ngcontent-ng-c2628602593="" class="btn main ng-star-inserted">...</button> is not clickable at point (1591, 19). Other element would receive the click: <nav _ngcontent-ng-c4030613539="">...</nav>
  (Session info: chrome=129.0.6668.100)
Stacktrace:
#0 0x5a3ff45c3b9a <unknown>
#1 0x5a3ff42a9670 <unknown>
#2 0x5a3ff42ff8c6 <unknown>
#3 0x5a3ff42fd7e6 <unknown>
#4 0x5a3ff42fb297 <unknown>
#5 0x5a3ff42fa6a6 <unknown>
#6 0x5a3ff42edae8 <unknown>
#7 0x5a3ff431db82 <unknown>
#8 0x5a3ff42ed4c8 <unknown>
#9 0x5a3ff431dd4e <unknown>
#10 0x5a3ff433cdd6 <unknown>
#11 0x5a3ff431d923 <unknown>
#12 0x5a3ff42eb6e7 <unknown>
#13 0x5a3ff42ec6de <unknown>
#14 0x5a3ff458d66b <unknown>
#15 0x5a3ff4591611 <unknown>
#16 0x5a3ff45794e5 <unknown>
#17 0x5a3ff4592192 <unknown>
#18 0x5a3ff455e6ef <unknown>
#19 0x5a3ff45b29d8 <unknown>
#20 0x5a3ff45b2ba7 <unknown>
#21 0x5a3ff45c29ec <unknown>
#22 0x7b995e3aa39d <unknown>
#23 0x7b995e42f49c <unknown>
```

**Comment by berndgz** [comment]
Dear @McTom234,
sorry, I can't reproduce the issue.
Did you use the AppImage, it includes all dependencies?
Do you have a native installation of the official Google Chrome build (no snap or flatpak, no Chromium or derivative)?
I tested with Google Chrome version 130.0.6723.58 (Official Build) (64-bit) and it worked without any issues (see screenshot and command-line log).
**It is important not to click anywhere else with the mouse during the Download!!!**

![Bildschirmfoto_vom_2024-10-20_10-41-50](https://github.com/user-attachments/assets/4e855c1e-822c-4012-911a-16c96ab3f60e)

```
found 1 addons.
- 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 0 rev 0
found '/home/bernd/Downloads/ffb777v2_native_2410.zip' addon archive.
install addon archive '/home/bernd/Downloads/ffb777v2_native_2410.zip' to path '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2' ...
backup addon archive '/home/bernd/Downloads/ffb777v2_native_2410.zip' ...
0
addon => (1, 'FlightFactor Boeing 777v2', 'ffb777v2_native_*.zip', '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2', 'XP12', 'Linux')
Addon obj. => 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 0 rev 0
found '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/a5b0d553-94d8-45d7-bffa-3fa87263ae5c.index' addon index.
- 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 2410 rev 1
```

**Comment by McTom234** [comment]
Thanks for the reply @berndgz

I used the AppImage.

I think the issue is specific to more than one entry (in my case the two stated above).

The issue only appears when trying to download the second plugin.

**Comment by berndgz** [comment]
Dear @McTom234,
sorry, again it works for me without issues (see screenshot and command-line log).

![Bildschirmfoto_vom_2024-10-20_11-54-39](https://github.com/user-attachments/assets/5130d1dd-d7c0-4d98-aa1e-964622a86c2e)

```
found 2 addons.
- 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 2410 rev 1
- 2, X-Plane 12, xplane12_native_*.zip, /home/bernd/X-Plane12/Custom Data, XP12, Linux, 0 rev 0
found '/home/bernd/Downloads/ffb777v2_native_2410.zip' addon archive.
found '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/a5b0d553-94d8-45d7-bffa-3fa87263ae5c.index' addon index.
path => /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2
delete file '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/./cycle_info.txt' ...
delete file '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/./cycle.json' ...
delete file '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/./nav1.db' ...
delete file '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/./nav2.db' ...
install addon archive '/home/bernd/Downloads/ffb777v2_native_2410.zip' to path '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2' ...
backup addon archive '/home/bernd/Downloads/ffb777v2_native_2410.zip' ...
0
found '/home/bernd/Downloads/xplane12_native_2410.zip' addon archive.
install addon archive '/home/bernd/Downloads/xplane12_native_2410.zip' to path '/home/bernd/X-Plane12/Custom Data' ...
backup addon archive '/home/bernd/Downloads/xplane12_native_2410.zip' ...
0
addon => (1, 'FlightFactor Boeing 777v2', 'ffb777v2_native_*.zip', '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2', 'XP12', 'Linux')
addon => (2, 'X-Plane 12', 'xplane12_native_*.zip', '/home/bernd/X-Plane12/Custom Data', 'XP12', 'Linux')
Addon obj. => 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 0 rev 0
Addon obj. => 2, X-Plane 12, xplane12_native_*.zip, /home/bernd/X-Plane12/Custom Data, XP12, Linux, 0 rev 0
found '/home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2/a5b0d553-94d8-45d7-bffa-3fa87263ae5c.index' addon index.
- 1, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /home/bernd/X-Plane12/Aircraft/FlightFactor Boeing 777v2, XP12, Linux, 2410 rev 1
found '/home/bernd/X-Plane12/Custom Data/17271467-ff15-4302-82a6-946b0ffe2aec.index' addon index.
- 2, X-Plane 12, xplane12_native_*.zip, /home/bernd/X-Plane12/Custom Data, XP12, Linux, 2410 rev 1
```
Can you provide a screenshot or video of which step it gets stuck on?

**Comment by berndgz** [comment]
Are there any leading or trailing white-spaces on the entries?

**Comment by McTom234** [comment]
No trailing/leading white-spaces.

![image](https://github.com/user-attachments/assets/818989ea-eb34-4fd0-877f-78c5a7e853e2)
This is where it throws the error. It already scrolled to the button (not in view, because of the warnings at the top) but only downloads the first plugin. When it scrolls to the button, the error is thrown - the moment where the download should start.

Here is more context to the log of the run:
```
addon => (1, 'X-Plane 12', 'xplane12_native_*.zip', '/usr/local/games/xplane12/Custom Data', 'XP12', 'Linux')
addon => (2, 'FlightFactor Boeing 777v2', 'ffb777v2_native_*.zip', '/usr/local/games/xplane12/Custom Data/STSFF/nav-data/ndbl/data', 'XP12', 'Linux')
Addon obj. => 1, X-Plane 12, xplane12_native_*.zip, /usr/local/games/xplane12/Custom Data, XP12, Linux, 0 rev 0
Addon obj. => 2, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /usr/local/games/xplane12/Custom Data/STSFF/nav-data/ndbl/data, XP12, Linux, 0 rev 0
found '/usr/local/games/xplane12/Custom Data/17271467-ff15-4302-82a6-946b0ffe2aec.index' addon index.
- 1, X-Plane 12, xplane12_native_*.zip, /usr/local/games/xplane12/Custom Data, XP12, Linux, 2410 rev 1
found '/usr/local/games/xplane12/Custom Data/STSFF/nav-data/ndbl/data/a5b0d553-94d8-45d7-bffa-3fa87263ae5c.index' addon index.
- 2, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /usr/local/games/xplane12/Custom Data/STSFF/nav-data/ndbl/data, XP12, Linux, 2410 rev 1
found 2 addons.
- 1, X-Plane 12, xplane12_native_*.zip, /usr/local/games/xplane12/Custom Data, XP12, Linux, 2410 rev 1
- 2, FlightFactor Boeing 777v2, ffb777v2_native_*.zip, /usr/local/games/xplane12/Custom Data/STSFF/nav-data/ndbl/data, XP12, Linux, 2410 rev 1
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "lnxngfmsdm_gui.py", line 360, in <lambda>
  File "lnxngfmsdm_core.py", line 233, in download
  File "selenium/webdriver/remote/webelement.py", line 94, in click
  File "selenium/webdriver/remote/webelement.py", line 395, in _execute
  File "selenium/webdriver/remote/webdriver.py", line 354, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button _ngcontent-ng-c2628602593="" class="btn main ng-star-inserted">...</button> is not clickable at point (1591, 19). Other element would receive the click: <nav _ngcontent-ng-c4030613539="">...</nav>
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5ee41f55b0aa <unknown>
#1 0x5ee41f0721a0 <unknown>
#2 0x5ee41f0c5896 <unknown>
#3 0x5ee41f0c382d <unknown>
#4 0x5ee41f0c12d7 <unknown>
#5 0x5ee41f0c06f1 <unknown>
#6 0x5ee41f0b3cf8 <unknown>
#7 0x5ee41f0e2d82 <unknown>
#8 0x5ee41f0b36d8 <unknown>
#9 0x5ee41f0e2f4e <unknown>
#10 0x5ee41f101866 <unknown>
#11 0x5ee41f0e2b23 <unknown>
#12 0x5ee41f0b1990 <unknown>
#13 0x5ee41f0b296e <unknown>
#14 0x5ee41f52716b <unknown>
#15 0x5ee41f52af68 <unknown>
#16 0x5ee41f51464c <unknown>
#17 0x5ee41f52bae7 <unknown>
#18 0x5ee41f4f94af <unknown>
#19 0x5ee41f5494f8 <unknown>
#20 0x5ee41f5496c0 <unknown>
#21 0x5ee41f559f26 <unknown>
#22 0x706f2006c39d <unknown>
#23 0x706f200f149c <unknown>
```

After the error, I have to close the browser manually (I guess selenium script died ?).

Here is my plugin config:
![image](https://github.com/user-attachments/assets/78adf092-74a1-4adb-9c9b-4ebb35084054)

**Comment by berndgz** [comment]
Dear @McTom234,
which version of Google Chrome do you have installed?

**Comment by McTom234** [comment]
It's 130.0.6723 in some testing variant (as it is selenium). The screenshot of Chrome contains more info. The last time I tried, I was running v129 but had the same error...

**Comment by berndgz** [comment]
Dear @McTom234,
which version of Linux and Desktop environment do you have installed?

**Comment by McTom234** [comment]
Hey @berndgz,

Operating System: Arch Linux 
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.4-zen2-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by berndgz** [comment]
Hey @McTom234 ,
how do you have installed the Google Chrome Webbrowser on Arch Linux?

**Comment by McTom234** [comment]
I installed it from the AUR using yay

**Comment by berndgz** [comment]
Hey @McTom234 ,

I have tested under Arch Linux with Google Chrome Web-Browser installed via yay and again with no issues.
It seems that there is a non-standard behavior on your system configuration related to the download dialog that captures the focus and then Selenium sends actions to that dialog instead of to the Navigraph Download page.
Please refer to the attached screenshot with the different behavior of the download dialog.
Maybe you can try to uninstall cleanup and reinstall the Google Chrome Web-Browser to restore standard behavior.

![lnxngfmsdm_issue_4](https://github.com/user-attachments/assets/40510136-54d9-4d5b-b1cf-1926331fcdce)

**Comment by berndgz** [comment]
Hey @McTom234 ,
I have added a Google Chrome pref related to the download bubble which should prevent the download dialog from appearing.
Maybe this will help in your system environment.
Please try version 1.0.1 and let me know if it solves the issue.

**Comment by McTom234** [comment]
But I just solved the issue.
The problem is apparently the sticky layout. I changed the order of the addons, so that the FF777 comes before the XP12. By doing so, Chrome only has to scroll down, in which case, the nav bar is not over the button to be clicked, which resolves the issue. Maybe that helps you fixing or reproducing the issue.

**Comment by berndgz** [comment]
Hey @McTom234 ,
Thank you for your solution, I have included it as a workaround in the usage instructions.
I can reproduce the issue now and will have a look for a final solution.

**Comment by berndgz** [comment]
Hey @McTom234 ,
I have changed selenium actions to the download website to ensure a safe processing.
Maybe this is a final solution.
Please try version 1.0.1 and let me know if it solves the issue.

**Comment by McTom234** [comment]
Hey @berndgz,
Thank you, works flawlessly!
